myapp/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/',views.SignUpView.as_view(),name='signup'),
]

myapp/myapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wings/', include('wings.urls')),
    path('accounts/',include('accounts.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('', RedirectView.as_view(url='/wings/')),
]

myapp/wings/urls.py
from django.urls import path
from . import views

app_name = 'wings'

urlpatterns = [
    path('',views.Index.as_view(),name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
]

myapp/auto_q_p/models.py
from django.db import models

# Create your models here.

myapp/wings/models.py
from django.db import models
#from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=255)
    author = models.ForeignKey(
        'auth.User',
        on_delete=models.CASCADE,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class Question(models.Model):
    name = models.CharField(max_length=255)
    author = models.ForeignKey(
        'auth.User',
        on_delete=models.CASCADE,
    )

    category = models.ForeignKey(
        Category,
        on_delete=models.PROTECT,
    )
    mondai = models.TextField(blank=True)
    seikai = models.TextField(blank=True)
    kaisetu = models.TextField(blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name



# Create your models here.

myapp/wings/forms.py
from django import forms

class SearchForm(forms.Form):
    keyword = forms.CharField(label='検索',max_length=100)

myapp/accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic

class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'
    

myapp/auto_q_p/views.py
from django.shortcuts import render
from ..wings from models

# Create your views here.
class Saiten(View):
    def get(self, request, *args, **kwargs):
        answer = request
        if answer == seikai :
            message = "正解!!"
        else:
            message = "不正解"
        context = {
            'message': message,
            'answer':answer,
            'seikai':question.seikai,
            'kaisetu': question.kaisetu,
        }
        return render(request, 'answer.html', context)

    def post(self, request, *args, **kwargs):
        answer = request
        if answer == seikai :
            message = "正解!!"
        else:
            message = "不正解"
        context = {
            'message': message,
            'answer':answer,
            'seikai':question.seikai,
            'kaisetu': question.kaisetu,
        }
        return render(request, 'answer.html', context)

saiten = Saiten.as_view()

myapp/wings/views.py
from django.shortcuts import render
from django.views import generic, View
from django.http import HttpResponse
from .models import Category, Question
from .forms import SearchForm

class Index(View):
    model =  Question
    template_name = 'index'
    def get(self,request,*args,**kwargs):
        searchForm = SearchForm(request.GET)
        if searchForm.is_valid():
            keyword = searchForm.cleaned_data['keyword']
            questions = Question.objects.filter(category__name__icontains=keyword)
        else:
            searchForm = SearchForm()
            questions = Question.objects.all()

        context = {
            'questions':questions,
            'searchForm':searchForm,
        }
        return render(request,'wings/index.html',context)

index_view = Index.as_view()

    #def get_queryset(self):
    #    return Question.objects.filter(category_name

class DetailView(generic.DetailView):
    model = Question

myapp/accounts/templates/accounts/signup.html
{% extends 'layout.html' %}

{% block content %}
<br>
<br>
<h1>Sign up（サインアップ）</h1>
<section class='common-form'>
    <form method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button type='submit'>Sign up（サインアップ）</button>
    </form>
</section>
{% endblock %}

myapp/auto_q_p/templates/auto_q_p/answer.html
{% extends './base.html' %}
{% block content %}
    <p>{{ question.category.name}}</p>
    <h1>{{ question.name }}</h1>
    <div>
        <p>{{ question.mondai|linebreaksbr }}</p>
                  <div>
                    <label for="answer">あなたの答え</label>
                    <p>{{ answer }}</p>
                    <p>正解は{{ seikai }}です。</p>
                    <p>{{ message }}</p>
                    <p>{% if kaisetu %}</p>
                        {{ kaisetu }}
                       {% endif %}
                  </div>
                    <a href='{% url "auto_q_p:question" %}' class='btn btn-outline-primary'>クリア</a>
                </div>
    </div>
    <div>
        <a href='{% url "wings:index" %}'>一覧</a>
    </div>

{% endblock %}

myapp/auto_q_p/templates/auto_q_p/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset='utf-8'>
        <meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>
        <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css'>

        <title>Wings</title>
        <style>body {padding-top: 80px;}</style>
    </head>
    <body>
        <nav class='navbar navber-expand-md navber-dark bg-dark fixed-top'>
            <a class='navber-brand' href='{% url "wings:index" %}'>Wings</a>
        </nav>
        <div class='container'>
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

myapp/auto_q_p/templates/auto_q_p/question.html
{% extends './base.html' %}
{% block content %}
    <p>{{ question.category.name}}</p>
    <h1>{{ question.name }}</h1>
    <div>
        <p>{{ question.mondai|linebreaksbr }}</p>

            <form action='{% url "auto_q_p:saiten" %}' method='post'>
                {% csrf_token %}
                <div class='form-group'>
                  <div>
                    <label for="answer">あなたの答え</label>
                    <textarea id="answer" name="answer">{{ answer }}</textarea>
                  </div>
                    <input type='submit' class='btn btn-outline-primary' value='正解を確認'>
                    <a href='{% url "auto_q_p:question" %}' class='btn btn-outline-secondary'>クリア</a>
                </div>
            </form>

    </div>
    <div>
        <a href='{% url "wings:index" %}'>一覧</a>
    </div>

{% endblock %}

myapp/templates/layout.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset='utf-8'>
        <meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>
        <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css'>
        
        <title>Wings</title>
        <style>body {padding-top: 80px;}</style>
    </head>
    <body>
        <nav class='navbar navber-expand-md navber-dark bg-dark fixed-top'>
            <a class='navber-brand' href='{% url "wings:index" %}'>Wings</a>
            <ul class='navbar-nav'>
                {% if user.is_authenticated %}
                    <li class='nav-item'>
                        <span class='navbar-text'>{{ user }} - </span>
                    </li>
                    <li class='nav-item'>
                        <a href='{% url "logout" %}' class='logout nav-link'>Logout（ログアウト）</a>
                    </li>
                {% else %}
                    <li class='nav-item'>
                        <a href='{% url "login" %}' class='login nav-link'>Login（ログイン）</a>
                    </li>
                    <li class='nav-item'>
                        <a href='{% url "accounts:signup" %}' class='signup nav-link'>Sign up（サインアップ）</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
        <div class='container'>
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

myapp/wings/templates/wings/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset='utf-8'>
        <meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>
        <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css'>
        
        <title>Wings</title>
        <style>body {padding-top: 80px;}</style>
    </head>
    <body>
        <nav class='navbar navber-expand-md navber-dark bg-dark fixed-top'>
            <a class='navber-brand' href='{% url "wings:index" %}'>Wings</a>
        </nav>
        <div class='container'>
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

myapp/wings/templates/wings/index.html
{% extends './base.html' %}
{% block content %}
    {% if searchForm %}
        <form action='{% url "wings:index" %}' method='get'>
            <div class='form-group'>
                {{ searchForm }}
                <input type='submit' class='btn btn-outline-primary' value='OK'>
                <a href='{% url "wings:index" %}' class='btn btn-outline-secondary'>クリア</a>
            </div>
        </form>
    {% endif %}
    <h1>問題一覧</h1>
    <table class='table table=striped table-hober'>
        <tr>
            <th>カテゴリ</th><th>単元</th>
        </tr>
        {% for question in questions %}
            <tr>
                <td>{{ question.category.name }}</td>
                <td><a href='{% url "wings:detail" question.pk %}'>{{ question.name }}</a></td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}
"""

                {% if age %}
                    <table class='table table=striped table-hober'>
                        <tr>
                            <th>カテゴリ</th><th>単元</th>
                        </tr>
　　　　　　　　　　　　{% object_lists = question.objects.filter(question.category__icontains='age')
                        {% for question in object_list %}
                            <tr>
                                <td>{{ question.category.name }}</td>
                                <td><a href='{% url "wings:detail" question.pk %}'>{{ question.name }}</a></td>
                            </tr>
                        {% endfor %}
                    </table>
                {% else %}
                    学年を選択してください
                    中学１年生　　　　　　　　    
                    中学２年生
                    中学３年生
　　　　　　　　　　<li class='nav-item'>
　　　　　　　　　　<span class='navbar-text'>{{ user }} - </span>
　　　　　　　　　　</li>
　　　　　　　　　　<li class='nav-item'>
                        <a href='{% url "logout" %}' class='logout nav-link'>Logout（ログアウト）</a>
                    </li>
                {% endif %}
"""

myapp/wings/templates/wings/question_detail.html
{% extends './base.html' %}
{% block content %}
    <p>{{ question.category.name}}</p>
    <h1>{{ question.name }}</h1>
    <div>        
        <p>{{ question.mondai|linebreaksbr }}</p>
        <p>正解と解説（必要な場合のみ）<p>
        <p>{{ question.seikai|linebreaksbr }}</p>
        <p>{{ question.kaisetu|linebreaksbr }}</p>        
    </div>
    <div>
        <a href='{% url "wings:index" %}'>一覧</a>
    </div>
    
{% endblock %}

myapp/wings/templates/wings/question_list.html
{% extends './base.html' %}
{% block content %}
    {% if searchForm %}
        <form action='{% url "wings:index" %}' method='get'>
            <div class='form-group'>
                {{ searchForm }}
                <input type='submit' class='btn btn-outline-primary' value='OK'>
                <a href='{% url "wings:index" %}' class='btn btn-outline-secondary'>クリア</a>
            </div>
        </form>
    {% endif %}
    <h1>問題一覧</h1>
    <table class='table table=striped table-hober'>
        <tr>
            <th>カテゴリ</th><th>単元</th>
        </tr>
        {% for question in object_list %}
            <tr>
                <td>{{ question.category.name }}</td>
                <td><a href='{% url "wings:detail" question.pk %}'>{{ question.name }}</a></td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}
"""

                {% if age %}
                    <table class='table table=striped table-hober'>
                        <tr>
                            <th>カテゴリ</th><th>単元</th>
                        </tr>
　　　　　　　　　　　　{% object_lists = question.objects.filter(question.category__icontains='age')
                        {% for question in object_list %}
                            <tr>
                                <td>{{ question.category.name }}</td>
                                <td><a href='{% url "wings:detail" question.pk %}'>{{ question.name }}</a></td>
                            </tr>
                        {% endfor %}
                    </table>
                {% else %}
                    学年を選択してください<li class='nav-item'>
                    中学１年生    <span class='navbar-text'>{{ user }} - </span>
                    中学２年生</li>
                    中学３年生<li class='nav-item'>
                        <a href='{% url "logout" %}' class='logout nav-link'>Logout（ログアウト）</a>
                    </li>
                {% endif %}
"""